[package]
name = "nsi"
version = "0.2.0"
authors = ["Moritz Moeller <virtualritz@gmail.com>"]
edition = "2018"
keywords = ["graphics", "vfx", "rendering", "nsi", "3delight"]
license-file = "LICENSE.md"
description = "High level bindings for Illumination Research’s Nodal Scene Interface – ɴsɪ."
homepage = "https://www.3delight.com/"
documentation = "https://nsi.readthedocs.io/"
repository = "https://github.com/virtualritz/nsi/"

[dependencies]
nsi-sys = "0.1.1"
enum_dispatch = "0.3.0"
