[package]
name = "nsi"
version = "0.3.0"
authors = ["Moritz Moeller <virtualritz@gmail.com>"]
edition = "2018"
keywords = ["graphics", "rendering", "3d", "ray-tracing", "scene-description"]
license = "BSD-3-Clause"
license-file = "LICENSE.md"
description = "High level bindings for Illumination Research’s Nodal Scene Interface – ɴsɪ."
readme = "README.md"
homepage = "https://www.3delight.com/"
documentation = "https://nsi.readthedocs.io/"
repository = "https://github.com/virtualritz/nsi/"

[dependencies]
nsi-sys = "0.1.1"
enum_dispatch = "0.3.0"
