[package]
name = "nsi-jupyter"
version = "0.6.1"
authors = ["Moritz Moeller <virtualritz@gmail.com>"]
edition = "2018"
keywords = ["graphics", "rendering", "3d", "ray-tracing", "scene-description"]
categories = ["graphics", "multimedia::images", "rendering::graphics-api"]
license = "MIT OR Apache-2.0 OR Zlib"
description = "Jypyter notebooks support for ɴsɪ."
readme = "README.md"
homepage = "https://www.3delight.com/"
documentation = "https://docs.rs/nsi/"
repository = "https://github.com/virtualritz/nsi/"

[dependencies]
nsi-core = { path = "../nsi-core", features = ["output"] }
base64 = "0.13.0"
bytemuck = "1.5.0"
evcxr_runtime = "1.1.0"
png = "0.17.2"
rayon = "1.5.0"
